quarkus.langchain4j.ollama.base-url=http://localhost:11434

quarkus.langchain4j.ollama.chat-model.model-id=mistral:7b-instruct-q4_0

quarkus.langchain4j.ollama.timeout=600s

# Aponta para o diretório que contém nossos documentos.
# O Easy RAG irá ler todos os arquivos neste local na inicialização.
quarkus.langchain4j.easy-rag.path=src/main/resources/rag